package com.chocksaway.bingo90.entities;

import org.apache.commons.lang3.tuple.ImmutablePair;

import java.util.Arrays;
import java.util.List;

public interface BingoData {

    List<ImmutablePair<Integer, Integer>> getBingoNumbers();

    int getTotal();

    List<ImmutablePair<Integer, Integer>> bingoNumbers =
            Arrays.<ImmutablePair<Integer, Integer>>asList(
            new ImmutablePair<>(1, 0),
            new ImmutablePair<>(2, 0),
            new ImmutablePair<>(3, 0),
            new ImmutablePair<>(4, 0),
            new ImmutablePair<>(5, 0),
            new ImmutablePair<>(6, 0),
            new ImmutablePair<>(7, 0),
            new ImmutablePair<>(8, 0),
            new ImmutablePair<>(9, 0),
            new ImmutablePair<>(10, 1),
            new ImmutablePair<>(11, 1),
            new ImmutablePair<>(12, 1),
            new ImmutablePair<>(13, 1),
            new ImmutablePair<>(14, 1),
            new ImmutablePair<>(15, 1),
            new ImmutablePair<>(16, 1),
            new ImmutablePair<>(17, 1),
            new ImmutablePair<>(18, 1),
            new ImmutablePair<>(19, 1),
            new ImmutablePair<>(20, 2),
            new ImmutablePair<>(21, 2),
            new ImmutablePair<>(22, 2),
            new ImmutablePair<>(23, 2),
            new ImmutablePair<>(24, 2),
            new ImmutablePair<>(25, 2),
            new ImmutablePair<>(26, 2),
            new ImmutablePair<>(27, 2),
            new ImmutablePair<>(28, 2),
            new ImmutablePair<>(29, 2),
            new ImmutablePair<>(30, 3),
            new ImmutablePair<>(31, 3),
            new ImmutablePair<>(32, 3),
            new ImmutablePair<>(33, 3),
            new ImmutablePair<>(34, 3),
            new ImmutablePair<>(35, 3),
            new ImmutablePair<>(36, 3),
            new ImmutablePair<>(37, 3),
            new ImmutablePair<>(38, 3),
            new ImmutablePair<>(39, 3),
            new ImmutablePair<>(40, 4),
            new ImmutablePair<>(41, 4),
            new ImmutablePair<>(42, 4),
            new ImmutablePair<>(43, 4),
            new ImmutablePair<>(44, 4),
            new ImmutablePair<>(45, 4),
            new ImmutablePair<>(46, 4),
            new ImmutablePair<>(47, 4),
            new ImmutablePair<>(48, 4),
            new ImmutablePair<>(49, 4),
            new ImmutablePair<>(50, 5),
            new ImmutablePair<>(51, 5),
            new ImmutablePair<>(52, 5),
            new ImmutablePair<>(53, 5),
            new ImmutablePair<>(54, 5),
            new ImmutablePair<>(55, 5),
            new ImmutablePair<>(56, 5),
            new ImmutablePair<>(57, 5),
            new ImmutablePair<>(58, 5),
            new ImmutablePair<>(59, 5),
            new ImmutablePair<>(60, 6),
            new ImmutablePair<>(61, 6),
            new ImmutablePair<>(62, 6),
            new ImmutablePair<>(63, 6),
            new ImmutablePair<>(64, 6),
            new ImmutablePair<>(65, 6),
            new ImmutablePair<>(66, 6),
            new ImmutablePair<>(67, 6),
            new ImmutablePair<>(68, 6),
            new ImmutablePair<>(69, 6),
            new ImmutablePair<>(70, 7),
            new ImmutablePair<>(71, 7),
            new ImmutablePair<>(72, 7),
            new ImmutablePair<>(73, 7),
            new ImmutablePair<>(74, 7),
            new ImmutablePair<>(75, 7),
            new ImmutablePair<>(76, 7),
            new ImmutablePair<>(77, 7),
            new ImmutablePair<>(78, 7),
            new ImmutablePair<>(79, 7),
            new ImmutablePair<>(80, 8),
            new ImmutablePair<>(81, 8),
            new ImmutablePair<>(82, 8),
            new ImmutablePair<>(83, 8),
            new ImmutablePair<>(84, 8),
            new ImmutablePair<>(85, 8),
            new ImmutablePair<>(86, 8),
            new ImmutablePair<>(87, 8),
            new ImmutablePair<>(88, 8),
            new ImmutablePair<>(89, 8),
            new ImmutablePair<>(90, 8)
    );
}
